-- Fitness App Database Setup Script for Oracle
-- This script creates the necessary tables and sample data for the fitness tracking application

-- Create Users table
CREATE TABLE USERS (
    USER_ID NUMBER(10) PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    PHONE VARCHAR2(15),
    DATE_OF_BIRTH DATE,
    GENDER VARCHAR2(10),
    HEIGHT NUMBER(5,2),
    WEIGHT NUMBER(5,2),
    ACTIVITY_LEVEL VARCHAR2(20),
    CREATED_DATE DATE DEFAULT SYSDATE,
    IS_ACTIVE NUMBER(1) DEFAULT 1
);

-- Create sequence for Users
CREATE SEQUENCE USER_ID_SEQ START WITH 1 INCREMENT BY 1;

-- Create trigger for auto-increment Users
CREATE OR REPLACE TRIGGER USER_ID_TRG
    BEFORE INSERT ON USERS
    FOR EACH ROW
BEGIN
    IF :NEW.USER_ID IS NULL THEN
        :NEW.USER_ID := USER_ID_SEQ.NEXTVAL;
    END IF;
END;
/

-- Create Fitness Plans table
CREATE TABLE FITNESS_PLANS (
    PLAN_ID NUMBER(10) PRIMARY KEY,
    USER_ID NUMBER(10) NOT NULL,
    PLAN_NAME VARCHAR2(100) NOT NULL,
    PLAN_DATE DATE NOT NULL,
    EXERCISE_TYPE VARCHAR2(50),
    DURATION_MINUTES NUMBER(10),
    CALORIES_BURNED NUMBER(8,2),
    SETS NUMBER(10),
    REPS NUMBER(10),
    WEIGHT_KG NUMBER(5,2),
    NOTES VARCHAR2(500),
    IS_COMPLETED NUMBER(1) DEFAULT 0,
    CREATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_FITNESS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Create sequence for Fitness Plans
CREATE SEQUENCE PLAN_ID_SEQ START WITH 1 INCREMENT BY 1;

-- Create trigger for auto-increment Fitness Plans
CREATE OR REPLACE TRIGGER PLAN_ID_TRG
    BEFORE INSERT ON FITNESS_PLANS
    FOR EACH ROW
BEGIN
    IF :NEW.PLAN_ID IS NULL THEN
        :NEW.PLAN_ID := PLAN_ID_SEQ.NEXTVAL;
    END IF;
END;
/

-- Create Diet Plans table
CREATE TABLE DIET_PLANS (
    DIET_ID NUMBER(10) PRIMARY KEY,
    USER_ID NUMBER(10) NOT NULL,
    MEAL_TYPE VARCHAR2(20) NOT NULL,
    MEAL_DATE DATE NOT NULL,
    FOOD_ITEM VARCHAR2(100) NOT NULL,
    QUANTITY VARCHAR2(50),
    CALORIES NUMBER(8,2),
    PROTEIN_G NUMBER(6,2),
    CARBS_G NUMBER(6,2),
    FAT_G NUMBER(6,2),
    FIBER_G NUMBER(6,2),
    SUGAR_G NUMBER(6,2),
    SODIUM_MG NUMBER(8,2),
    NOTES VARCHAR2(500),
    IS_CONSUMED NUMBER(1) DEFAULT 0,
    CREATED_DATE DATE DEFAULT SYSDATE,
    CONSTRAINT FK_DIET_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Create sequence for Diet Plans
CREATE SEQUENCE DIET_ID_SEQ START WITH 1 INCREMENT BY 1;

-- Create trigger for auto-increment Diet Plans
CREATE OR REPLACE TRIGGER DIET_ID_TRG
    BEFORE INSERT ON DIET_PLANS
    FOR EACH ROW
BEGIN
    IF :NEW.DIET_ID IS NULL THEN
        :NEW.DIET_ID := DIET_ID_SEQ.NEXTVAL;
    END IF;
END;
/

-- Create OTP Verifications table
CREATE TABLE OTP_VERIFICATIONS (
    OTP_ID NUMBER(10) PRIMARY KEY,
    USER_ID NUMBER(10) NOT NULL,
    OTP_CODE VARCHAR2(6) NOT NULL,
    GENERATED_AT DATE DEFAULT SYSDATE,
    EXPIRES_AT DATE NOT NULL,
    IS_USED NUMBER(1) DEFAULT 0,
    USED_AT DATE,
    PURPOSE VARCHAR2(20) DEFAULT 'LOGIN',
    CONSTRAINT FK_OTP_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- Create sequence for OTP Verifications
CREATE SEQUENCE OTP_ID_SEQ START WITH 1 INCREMENT BY 1;

-- Create trigger for auto-increment OTP Verifications
CREATE OR REPLACE TRIGGER OTP_ID_TRG
    BEFORE INSERT ON OTP_VERIFICATIONS
    FOR EACH ROW
BEGIN
    IF :NEW.OTP_ID IS NULL THEN
        :NEW.OTP_ID := OTP_ID_SEQ.NEXTVAL;
    END IF;
END;
/

-- Insert demo user (password is "demo123" hashed with SHA256)
INSERT INTO USERS (USERNAME, PASSWORD_HASH, EMAIL, FIRST_NAME, LAST_NAME, PHONE, DATE_OF_BIRTH, GENDER, HEIGHT, WEIGHT, ACTIVITY_LEVEL)
VALUES ('demo_user', 'k4rsLvl17jDSfgSDflSDf2SDfCXvN6uvBx5Q0qvVQ=', 'demo@example.com', 'John', 'Doe', '+1234567890', TO_DATE('1990-01-15', 'YYYY-MM-DD'), 'Male', 175.50, 75.0, 'Moderate');

-- Insert sample fitness plans for demo user
INSERT INTO FITNESS_PLANS (USER_ID, PLAN_NAME, PLAN_DATE, EXERCISE_TYPE, DURATION_MINUTES, CALORIES_BURNED, SETS, REPS, NOTES, IS_COMPLETED)
VALUES (1, 'Morning Cardio', SYSDATE, 'Cardio', 30, 250, NULL, NULL, 'Treadmill running at moderate pace', 1);

INSERT INTO FITNESS_PLANS (USER_ID, PLAN_NAME, PLAN_DATE, EXERCISE_TYPE, DURATION_MINUTES, CALORIES_BURNED, SETS, REPS, WEIGHT_KG, NOTES, IS_COMPLETED)
VALUES (1, 'Chest and Triceps', SYSDATE, 'Strength', 45, 180, 3, 12, 40.0, 'Bench press and tricep dips', 0);

INSERT INTO FITNESS_PLANS (USER_ID, PLAN_NAME, PLAN_DATE, EXERCISE_TYPE, DURATION_MINUTES, CALORIES_BURNED, NOTES, IS_COMPLETED)
VALUES (1, 'Evening Yoga', SYSDATE, 'Flexibility', 25, 80, 'Relaxing yoga session for flexibility', 0);

-- Insert sample diet plans for demo user
INSERT INTO DIET_PLANS (USER_ID, MEAL_TYPE, MEAL_DATE, FOOD_ITEM, QUANTITY, CALORIES, PROTEIN_G, CARBS_G, FAT_G, FIBER_G, IS_CONSUMED)
VALUES (1, 'Breakfast', SYSDATE, 'Oatmeal with Banana', '1 bowl', 320, 12.0, 58.0, 6.0, 8.0, 1);

INSERT INTO DIET_PLANS (USER_ID, MEAL_TYPE, MEAL_DATE, FOOD_ITEM, QUANTITY, CALORIES, PROTEIN_G, CARBS_G, FAT_G, FIBER_G, IS_CONSUMED)
VALUES (1, 'Breakfast', SYSDATE, 'Greek Yogurt', '1 cup', 150, 20.0, 9.0, 4.0, 0.0, 1);

INSERT INTO DIET_PLANS (USER_ID, MEAL_TYPE, MEAL_DATE, FOOD_ITEM, QUANTITY, CALORIES, PROTEIN_G, CARBS_G, FAT_G, FIBER_G, IS_CONSUMED)
VALUES (1, 'Lunch', SYSDATE, 'Grilled Chicken Salad', '1 plate', 400, 35.0, 15.0, 18.0, 6.0, 0);

INSERT INTO DIET_PLANS (USER_ID, MEAL_TYPE, MEAL_DATE, FOOD_ITEM, QUANTITY, CALORIES, PROTEIN_G, CARBS_G, FAT_G, FIBER_G, IS_CONSUMED)
VALUES (1, 'Dinner', SYSDATE, 'Salmon with Rice', '1 serving', 550, 40.0, 45.0, 20.0, 3.0, 0);

INSERT INTO DIET_PLANS (USER_ID, MEAL_TYPE, MEAL_DATE, FOOD_ITEM, QUANTITY, CALORIES, PROTEIN_G, CARBS_G, FAT_G, FIBER_G, IS_CONSUMED)
VALUES (1, 'Snack', SYSDATE, 'Mixed Nuts', '1 handful', 180, 6.0, 8.0, 16.0, 4.0, 0);

-- Create indexes for better performance
CREATE INDEX IDX_FITNESS_USER_DATE ON FITNESS_PLANS (USER_ID, PLAN_DATE);
CREATE INDEX IDX_DIET_USER_DATE ON DIET_PLANS (USER_ID, MEAL_DATE);
CREATE INDEX IDX_OTP_USER_CODE ON OTP_VERIFICATIONS (USER_ID, OTP_CODE);

-- Create a procedure to clean up expired OTPs
CREATE OR REPLACE PROCEDURE CLEANUP_EXPIRED_OTPS
IS
BEGIN
    DELETE FROM OTP_VERIFICATIONS 
    WHERE EXPIRES_AT < SYSDATE AND IS_USED = 0;
    
    COMMIT;
END CLEANUP_EXPIRED_OTPS;
/

-- Create a function to calculate BMI
CREATE OR REPLACE FUNCTION CALCULATE_BMI(p_weight NUMBER, p_height NUMBER)
RETURN NUMBER
IS
    v_bmi NUMBER;
BEGIN
    IF p_weight IS NULL OR p_height IS NULL OR p_height = 0 THEN
        RETURN NULL;
    END IF;
    
    v_bmi := p_weight / POWER((p_height / 100), 2);
    RETURN ROUND(v_bmi, 2);
END CALCULATE_BMI;
/

-- Grant necessary permissions (run as DBA)
-- GRANT CREATE SESSION TO fitness_app;
-- GRANT CREATE TABLE TO fitness_app;
-- GRANT CREATE SEQUENCE TO fitness_app;
-- GRANT CREATE TRIGGER TO fitness_app;
-- GRANT CREATE PROCEDURE TO fitness_app;
-- GRANT CREATE FUNCTION TO fitness_app;

COMMIT;

PROMPT 'Database setup completed successfully!'
PROMPT 'Demo user credentials:'
PROMPT 'Username: demo_user'
PROMPT 'Password: demo123'